// Portfolio data — keep this in one place so adding projects is easy.

window.PORTFOLIO_DATA = {
  hero: {
    name: "WANDERER",
    epithet: "Of the Code-Forged",
    subtitle: "Designer · Engineer · Apprentice of the Loop",
  },

  // Projects (gemstones). To add: append an object. Constellation positions
  // (xp, yp) are percentages (0–100) of the constellation canvas. Pick spots
  // that feel like a real star field — slight asymmetry is the goal.
  projects: [
    {
      id: "blinkbeat",
      name: "Blink Beat",
      epithet: "Glaive of the Pulse",
      type: "Rhythm Vessel",
      rarity: "Rare",
      hue: 16,         // 0–360 hsl
      shape: "kite",   // kite | hex | oval | shard | teardrop | diamond | obelisk
      stats: { ATK: 47, FAITH: 18, ARC: 31, SPD: 62 },
      tags: ["React", "Web Audio", "Game Loop"],
      desc: "A rhythm-driven micro-game where each blink syncs the next beat. Forged to teach intuition through latency.",
      github: "https://github.com/",
      xp: 14, yp: 28,
    },
    {
      id: "csnight",
      name: "CSNight",
      epithet: "Ledger of the Vigil",
      type: "Event Tome",
      rarity: "Common",
      hue: 220,
      shape: "hex",
      stats: { ATK: 22, FAITH: 41, ARC: 28, SPD: 35 },
      tags: ["Next.js", "Tailwind", "CMS"],
      desc: "Annual student-org night-of-CS site. Schedules, talks, RSVPs — kept alive through three regimes of organizers.",
      github: "https://github.com/",
      xp: 38, yp: 18,
    },
    {
      id: "meowchi",
      name: "Meowchi",
      epithet: "Whisker of the Hearth",
      type: "Freelance Sigil",
      rarity: "Uncommon",
      hue: 340,
      shape: "teardrop",
      stats: { ATK: 33, FAITH: 51, ARC: 22, SPD: 48 },
      tags: ["Freelance", "E-commerce", "Brand"],
      desc: "Storefront for a small bakery. Soft palette, careful motion. Real customers, real receipts.",
      github: "https://github.com/",
      xp: 56, yp: 28,
    },
    {
      id: "ihalalan",
      name: "iHalalan",
      epithet: "Compass of the Faithful",
      type: "Civic Talisman",
      rarity: "Rare",
      hue: 140,
      shape: "diamond",
      stats: { ATK: 28, FAITH: 64, ARC: 42, SPD: 30 },
      tags: ["Civic Tech", "Maps", "PWA"],
      desc: "Locator and verifier for halal establishments. A small map made with care for the people it serves.",
      github: "https://github.com/",
      xp: 86, yp: 26,
    },
    {
      id: "quizgive",
      name: "QuizGive",
      epithet: "Token of the Open Hand",
      type: "Pedagogy Relic",
      rarity: "Uncommon",
      hue: 48,
      shape: "shard",
      stats: { ATK: 36, FAITH: 39, ARC: 55, SPD: 41 },
      tags: ["EdTech", "Donations", "Quiz Engine"],
      desc: "A quiz platform where right answers fund causes. Learning that gives back, by design.",
      github: "https://github.com/",
      xp: 22, yp: 70,
    },
    {
      id: "oversee",
      name: "OverSee",
      epithet: "Eye of the Ledger",
      type: "Watchstone",
      rarity: "Rare",
      hue: 280,
      shape: "obelisk",
      stats: { ATK: 44, FAITH: 23, ARC: 58, SPD: 39 },
      tags: ["Monitoring", "Dashboard", "Realtime"],
      desc: "An overseer's dashboard. Quiet when calm, loud when the floor is shifting.",
      github: "https://github.com/",
      xp: 50, yp: 78,
    },
    {
      id: "azerotech",
      name: "Azerotech",
      epithet: "Sigil of Commerce",
      type: "Freelance Sigil",
      rarity: "Uncommon",
      hue: 200,
      shape: "oval",
      stats: { ATK: 31, FAITH: 27, ARC: 36, SPD: 53 },
      tags: ["Freelance", "Corporate", "Marketing"],
      desc: "Corporate site for a tech consultancy. Sober, fast, easy to maintain — exactly the brief.",
      github: "https://github.com/",
      xp: 78, yp: 76,
    },
  ],

  // Connections between gemstones in the constellation
  constellationEdges: [
    ["blinkbeat", "csnight"],
    ["csnight", "meowchi"],
    ["meowchi", "ihalalan"],
    ["ihalalan", "oversee"],
    ["oversee", "azerotech"],
    ["quizgive", "blinkbeat"],
    ["quizgive", "oversee"],
    ["csnight", "quizgive"],
  ],

  achievements: {
    title: "CHRONICLE OF DEEDS",
    level: 6,
    runes: 12480,
    class: "Director of Outreach",
    stats: [
      { key: "VIGOR",        val: 24, note: "Endurance through trials" },
      { key: "MIND",         val: 31, note: "Recall of the codices" },
      { key: "INTELLIGENCE", val: 28, note: "Spell-craft and reasoning" },
      { key: "FAITH",        val: 42, note: "Conviction in the cause" },
      { key: "DEXTERITY",    val: 35, note: "Swift hands at the keys" },
      { key: "ARCANE",       val: 38, note: "Strange knowing of systems" },
    ],
    timeline: [
      { year: "2023–2024", title: "Junior Officer of Publicity",      org: "FEU Tech · ACM",
        body: "Apprenticeship taken. Tasked with raising the banner of the chapter; learned the craft of summoning crowds." },
      { year: "2024–2025", title: "Director for Outreach",            org: "FEU Tech · ACM",
        body: "Carried the chapter beyond its walls. Forged ties with neighboring guilds and lesser strongholds." },
      { year: "2025",      title: "Best Outreach Activity",           org: "FEU Tech (Award)",
        body: "A laurel awarded for the year's outreach campaign. The hall remembers." },
      { year: "2025–2026", title: "Director for Marketing",           org: "FEU Tech · ACM",
        body: "Tasked with the chapter's voice. Each banner, post, and sigil passed beneath this hand." },
      { year: "2026",      title: "President",                         org: "FEU Tech · ACM",
        body: "The seat at the head of the round table. Stewardship of the order." },
    ],
  },

  contact: {
    intro: "Inscribe thy name and thy summons upon the stone. Such words travel far.",
    handles: [
      { label: "GitHub",   value: "/wanderer" },
      { label: "LinkedIn", value: "/in/wanderer" },
      { label: "Email",    value: "wanderer@lands.between" },
    ],
  },
};
